# Generated by Django 2.0 on 2019-12-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genoma',
            options={'verbose_name': 'Doença', 'verbose_name_plural': 'Doenças'},
        ),
    ]
