# Generated by Django 2.0 on 2019-12-14 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genoma',
            name='name',
        ),
        migrations.AddField(
            model_name='genoma',
            name='disease',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Genes da doença'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genoma',
            name='gene',
            field=models.CharField(max_length=50, verbose_name='Nome da Doença'),
        ),
    ]
