# Generated by Django 2.0 on 2019-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0002_auto_20191214_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.CharField(max_length=50, verbose_name='Nome da Doença'),
        ),
        migrations.AlterField(
            model_name='genoma',
            name='gene',
            field=models.CharField(max_length=100, verbose_name='Genes da doença'),
        ),
    ]
