# Generated by Django 2.0 on 2019-12-13 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Genoma', '0002_auto_20191213_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='genoma',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Nome da Doença'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.CharField(max_length=100, verbose_name='Descrição da doença'),
        ),
    ]
