# Generated by Django 2.0 on 2019-12-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genoma', '0003_auto_20191213_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descrição da doença'),
        ),
    ]
