# Generated by Django 2.0 on 2019-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0003_auto_20191214_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.CharField(max_length=100, verbose_name='Nome da Doença'),
        ),
    ]
