# Generated by Django 2.0 on 2019-12-13 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Genoma', '0004_auto_20191213_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='genoma',
            name='gene',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Genes da doença'),
            preserve_default=False,
        ),
    ]
