# Generated by Django 2.0 on 2019-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0004_auto_20191214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.CharField(max_length=200, verbose_name='Nome da Doença'),
        ),
        migrations.AlterField(
            model_name='genoma',
            name='gene',
            field=models.CharField(max_length=200, verbose_name='Genes da doença'),
        ),
    ]
