# Generated by Django 2.0 on 2019-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genoma', '0005_auto_20191214_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genoma',
            name='disease',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome da Doença'),
        ),
        migrations.AlterField(
            model_name='genoma',
            name='gene',
            field=models.CharField(max_length=200, null=True, verbose_name='Genes da doença'),
        ),
    ]
