# Generated by Django 2.0 on 2019-12-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genoma', '0005_genoma_gene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genoma',
            name='disease',
        ),
    ]
