version: '3'
services:
  db:
    image: postgres
  genomika:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: Genomika
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
